# Generated by Django 5.1.7 on 2025-04-20 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="profiles.shippingaddress",
            ),
        ),
        migrations.DeleteModel(
            name="ShippingAddress",
        ),
    ]
