# Generated by Django 5.1.7 on 2025-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_shipping_address_delete_shippingaddress"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="shipping_address",
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address1",
            field=models.CharField(
                default="", max_length=255, verbose_name="Address Line 1"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address2",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Address Line 2"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(default="", max_length=100, verbose_name="City"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(default="", max_length=100, verbose_name="Country"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_email",
            field=models.EmailField(default="", max_length=254, verbose_name="Email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_full_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Full Name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Phone Number"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_state",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="State/Province"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zipcode",
            field=models.CharField(
                default="", max_length=20, verbose_name="ZIP/Postal Code"
            ),
            preserve_default=False,
        ),
    ]
